# -*- coding: utf-8 -*-
"""ALMA_JoLA_Yoruba_Dialect_MT

Automatically generated by Colab.


# ALMA-7B + JoLA — Yoruba Dialects Machine Translation
Translating **Std Yoruba**, **Ilaje**, and **Ife** dialects to English
using JoLA (LoFiT adapters) on `haoranxu/ALMA-7B`.

## Step 1 — Mount Drive & Install Dependencies
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q jola
!pip install -q git+https://github.com/wenlai-lavine/jola.git
!wget -q https://raw.githubusercontent.com/wenlai-lavine/jola/main/jola/config.yaml \
    -O /usr/local/lib/python3.12/dist-packages/jola/config.yaml
!pip install -q transformers>=4.45.0
!pip install -q sacrebleu bert-score rouge-score

import os
config_path = '/usr/local/lib/python3.12/dist-packages/jola/config.yaml'
print('Config found!' if os.path.exists(config_path) else 'Config NOT found!')
print('All dependencies installed!')

"""## Step 2 — Load & Format Dataset
ALMA prompt format: `Translate this from {dialect} Yoruba to English:\n{dialect} Yoruba: {text}\nEnglish:`
The `English:` trigger forces ALMA to output English.
"""

import pandas as pd

# Load dataset
df = pd.read_csv('/content/drive/MyDrive/yorulect.csv')

print('Shape:', df.shape)
print('Columns:', df.columns.tolist())
df.head()

# Format each dialect using ALMA official prompt format
def format_data(df, source_col, dialect_name):
    data = []
    for _, row in df.iterrows():
        if pd.notna(row[source_col]) and pd.notna(row['english_text']):
            data.append({
                'instruction': f'Translate this from {dialect_name} Yoruba to English:\n{dialect_name} Yoruba: {row[source_col]}\nEnglish:',
                'answer': row['english_text']
            })
    return data

std_data   = format_data(df, 'std yoruba transcription', 'Standard')
ilaje_data = format_data(df, 'Ilaje transcription',      'Ilaje')
ife_data   = format_data(df, 'Ife transcription',        'Ife')

print(f'Std Yoruba : {len(std_data)} samples')
print(f'Ilaje      : {len(ilaje_data)} samples')
print(f'Ife        : {len(ife_data)} samples')
print('\nSample instruction:')
print(std_data[0]['instruction'])
print('Answer:', std_data[0]['answer'])

"""## Step 3 — Split into Train / Valid / Test"""

from sklearn.model_selection import train_test_split

def split_data(data, random_state=42):
    train, temp = train_test_split(data, test_size=0.2, random_state=random_state)
    valid, test = train_test_split(temp, test_size=0.5, random_state=random_state)
    return train, valid, test

std_train,   std_valid,   std_test   = split_data(std_data)
ilaje_train, ilaje_valid, ilaje_test = split_data(ilaje_data)
ife_train,   ife_valid,   ife_test   = split_data(ife_data)

# Combine all dialects for joint training
combined_train = std_train + ilaje_train + ife_train
combined_valid = std_valid + ilaje_valid + ife_valid
combined_test  = std_test  + ilaje_test  + ife_test

print(f'Std   — Train: {len(std_train)}, Valid: {len(std_valid)}, Test: {len(std_test)}')
print(f'Ilaje — Train: {len(ilaje_train)}, Valid: {len(ilaje_valid)}, Test: {len(ilaje_test)}')
print(f'Ife   — Train: {len(ife_train)}, Valid: {len(ife_valid)}, Test: {len(ife_test)}')
print(f'\nCombined — Train: {len(combined_train)}, Valid: {len(combined_valid)}, Test: {len(combined_test)}')

"""## Step 4 — Update JoLA Config & Load ALMA Model
##### Train and valid sets were merged for JoLA training, resulting in 2,700 training samples (2,400 train + 300 valid) across all three dialects combined for joint training
"""

import sys, os, torch, warnings, yaml
from jola import JoLAConfig, JoLAModel
from transformers import AutoTokenizer

warnings.filterwarnings('ignore')
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

MODEL_NAME  = 'haoranxu/ALMA-7B'
config_path = '/usr/local/lib/python3.12/dist-packages/jola/config.yaml'

# Update JoLA config
with open(config_path, 'r') as f:
    config = yaml.safe_load(f)

config['model_config']['pretrained_model_name_or_path'] = MODEL_NAME
config['training_config'].pop('max_seq_length', None)

with open(config_path, 'w') as f:
    yaml.dump(config, f)

print(f'Config updated — model: {MODEL_NAME}')

# Load JoLA config
jola_config = JoLAConfig.get_jola_config(default=True)

# Load tokenizer
jola_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
jola_tokenizer.padding_side = 'right'

# Add padding token if missing
if jola_tokenizer.pad_token is None:
    jola_tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    print('Padding token added!')

# Load ALMA with JoLA adapters — works natively (ALMA is LLaMA-based)
jola_model = JoLAModel.jola_from_pretrained(**jola_config['model_config'])
jola_model.unfreeze_jola_params()
jola_model.model.train()

# Resize embeddings if padding token was added
if jola_tokenizer.pad_token == '[PAD]':
    jola_model.resize_token_embeddings(jola_model.config.vocab_size + 1)

# Reset gates to zero — prevents NaN during training
for module in jola_model.modules():
    if hasattr(module, 'log_g1'):
        module.log_g1.data.fill_(0.0)
        module.log_g2.data.fill_(0.0)

print('Gates reset to zero!')

# Show trainable params
total     = sum(p.numel() for p in jola_model.parameters())
trainable = sum(p.numel() for p in jola_model.parameters() if p.requires_grad)
print(f'Model           : {MODEL_NAME}')
print(f'Total params    : {total:,}')
print(f'Trainable params: {trainable:,} ({100*trainable/total:.2f}%)')

"""## Step 5 — Prepare Dataset & Train"""

from jola import JoLATrainer, JoLADataset, make_data_collator
from transformers import TrainingArguments

all_data = combined_train + combined_valid

data_collator = make_data_collator(tokenizer=jola_tokenizer)
jola_dataset  = JoLADataset(train_list=all_data, train_size=0)
jola_data     = jola_dataset.data_from_list()

print('Dataset loaded!')
print('Train:', len(jola_data['train']))

# Training args
training_args = TrainingArguments(
    output_dir='./alma_jola_output',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=2,     # effective batch = 16
    learning_rate=5e-4,
    warmup_steps=50,
    weight_decay=0.01,
    evaluation_strategy='no',
    save_strategy='epoch',
    logging_steps=10,
    lr_scheduler_type='cosine',
    fp16=False,                        # float32
    bf16=False,
    max_grad_norm=1.0,                 # gradient clipping
)

jola_trainer = JoLATrainer(
    jola_model,
    train_dataset=jola_data['train'],
    eval_dataset=None,
    tokenizer=jola_tokenizer,
    data_collator=data_collator,
    args=training_args,
    callbacks=[],
    gate_scheduler=False
)

# Required — L0 sparsity regularization
jola_trainer.gated_lambda = 0.01

print('Trainer ready!')
print(f'  Model     : {MODEL_NAME}')
print(f'  Epochs    : {training_args.num_train_epochs}')
print(f'  LR        : {training_args.learning_rate}')
print(f'  Batch size: {training_args.per_device_train_batch_size}')
print(f'  Eff. batch: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}')
print(f'  FP16      : {training_args.fp16}')

batch = next(iter(jola_trainer.get_train_dataloader()))
print("Keys:", batch.keys())
print("input_ids shape:", batch['input_ids'].shape)
print("labels unique:", batch['labels'].unique())
print("labels:", batch['labels'][0][:20])

from transformers import DataCollatorForLanguageModeling
data_collator = DataCollatorForLanguageModeling(
    tokenizer=jola_tokenizer,
    mlm=False
)

jola_trainer = JoLATrainer(
    jola_model,
    train_dataset=jola_data['train'],
    eval_dataset=None,
    tokenizer=jola_tokenizer,
    data_collator=data_collator,
    args=training_args,
    callbacks=[],
    gate_scheduler=False
)
jola_trainer.gated_lambda = 0.01

print('Starting training...')
jola_trainer.train()
print('Training complete!')

"""## Step 6 — Inference on Test Set"""

# Set model to eval mode
jola_model.eval()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
jola_model.to(device)
print('Device:', device)

def run_inference(model, tokenizer, data, dialect_name):
    predictions, references = [], []
    print(f'\nRunning inference for {dialect_name}...')

    with torch.no_grad():
        for item in data:
            inputs = tokenizer(
                item['instruction'],
                return_tensors='pt',
                truncation=True,
                max_length=512
            ).to(device)

            input_len = inputs['input_ids'].shape[1]

            outputs = model.generate(
                **inputs,
                max_new_tokens=128,
                num_beams=4,
                early_stopping=True,
                no_repeat_ngram_size=3,
                repetition_penalty=1.3,
                pad_token_id=tokenizer.eos_token_id
            )

            # Decode only generated part — skip the instruction
            pred = tokenizer.decode(outputs[0][input_len:], skip_special_tokens=True)
            predictions.append(pred.strip())
            references.append(item['answer'])

    print(f'{dialect_name} — {len(predictions)} samples predicted')
    return predictions, references

def run_inference(model, tokenizer, data, dialect_name):
    predictions, references = [], []
    print(f'\nRunning inference for {dialect_name}...')

    with torch.no_grad():
        for i, item in enumerate(data):
            try:
                inputs = tokenizer(
                    item['instruction'],
                    return_tensors='pt',
                    truncation=True,
                    max_length=256
                ).to(device)

                input_len = inputs['input_ids'].shape[1]

                outputs = model.generate(
                    **inputs,
                    max_new_tokens=64,
                    num_beams=1,
                    do_sample=False,
                    pad_token_id=tokenizer.eos_token_id
                )

                pred = tokenizer.decode(outputs[0][input_len:], skip_special_tokens=True)
                predictions.append(pred.strip())
                references.append(item['answer'])

                if (i+1) % 10 == 0:
                    print(f'  {i+1}/{len(data)} done...')

            except Exception as e:
                print(f'  Sample {i} skipped: {e}')
                predictions.append('')
                references.append(item['answer'])

    print(f'{dialect_name} — {len(predictions)} samples predicted')
    return predictions, references

# Run inference per dialect
std_preds,   std_refs   = run_inference(jola_model, jola_tokenizer, std_test,   'Std Yoruba')
ilaje_preds, ilaje_refs = run_inference(jola_model, jola_tokenizer, ilaje_test, 'Ilaje')
ife_preds,   ife_refs   = run_inference(jola_model, jola_tokenizer, ife_test,   'Ife')

# Preview predictions vs references
def preview(predictions, references, dialect_name, n=3):
    print(f'\n── {dialect_name} Predictions')
    for i in range(min(n, len(predictions))):
        print(f'  Reference : {references[i]}')
        print(f'  Predicted : {predictions[i]}')
        print()

preview(std_preds,   std_refs,   'Std Yoruba')
preview(ilaje_preds, ilaje_refs, 'Ilaje')
preview(ife_preds,   ife_refs,   'Ife')

"""## Step 7 — Evaluation Metrics"""

import numpy as np
from sacrebleu.metrics import BLEU, CHRF, TER
from bert_score import score as bert_score
from rouge_score import rouge_scorer

def compute_metrics(predictions, references, dialect_name):
    # BLEU
    bleu_score = BLEU().corpus_score(predictions, [references]).score

    # chrF+ (word_order=1)
    chrf_score = CHRF(word_order=1).corpus_score(predictions, [references]).score

    # BERTScore F1
    _, _, F1 = bert_score(predictions, references, lang='en', verbose=False)
    bertscore_f1 = F1.mean().item()

    # ROUGE-L
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rougeL = np.mean([
        scorer.score(ref, pred)['rougeL'].fmeasure
        for ref, pred in zip(references, predictions)
    ])

    # TER (lower is better)
    ter_score = TER().corpus_score(predictions, [references]).score

    print(f'\n── {dialect_name} Metrics')
    print(f'  BLEU         : {bleu_score:.2f}')
    print(f'  chrF+        : {chrf_score:.2f}')
    print(f'  BERTScore F1 : {bertscore_f1:.4f}')
    print(f'  ROUGE-L      : {rougeL:.4f}')
    print(f'  TER (↓)      : {ter_score:.2f}')

    return {
        'Dialect'      : dialect_name,
        'BLEU'         : round(bleu_score, 2),
        'chrF+'        : round(chrf_score, 2),
        'BERTScore F1' : round(bertscore_f1, 4),
        'ROUGE-L'      : round(rougeL, 4),
        'TER (↓)'      : round(ter_score, 2)
    }

# Evaluate each dialect
std_metrics   = compute_metrics(std_preds,   std_refs,   'Std Yoruba')
ilaje_metrics = compute_metrics(ilaje_preds, ilaje_refs, 'Ilaje')
ife_metrics   = compute_metrics(ife_preds,   ife_refs,   'Ife')

# Summary table
results_df = pd.DataFrame([std_metrics, ilaje_metrics, ife_metrics])
results_df = results_df.set_index('Dialect')

print('\n── Final Results Summary')
print(results_df.to_string())

# Save results
results_df.to_csv('/content/alma_jola_metrics_results.csv')
print('\nSaved to /content/alma_jola_metrics_results.csv')

import pandas as pd

# ── Load results as dataframe ─────────────────────────────
results_df = pd.read_csv('/content/alma_jola_metrics_results.csv', index_col='Dialect')

print('Results loaded!')
print(results_df)
print('\nShape:', results_df.shape)

# ── Save predictions first ────────────────────────────────
def save_predictions(preds, refs, test_data, filename):
    rows = []
    for pred, ref, item in zip(preds, refs, test_data):
        source = item['instruction'].split('\n')[1].split(': ', 1)[-1]
        rows.append({
            'source_yoruba'     : source,
            'reference_english' : ref,
            'predicted_english' : pred
        })
    df = pd.DataFrame(rows)
    df.to_csv(filename, index=False)
    return df

std_df   = save_predictions(std_preds,   std_refs,   std_test,   '/content/std_predictions.csv')
ilaje_df = save_predictions(ilaje_preds, ilaje_refs, ilaje_test, '/content/ilaje_predictions.csv')
ife_df   = save_predictions(ife_preds,   ife_refs,   ife_test,   '/content/ife_predictions.csv')

# ── Preview each
print('── Std Yoruba')
print(std_df.head(3).to_string())

print('\n── Ilaje')
print(ilaje_df.head(3).to_string())

print('\n── Ife')
print(ife_df.head(3).to_string())

import pandas as pd

data = pd.read_csv("/content/std_predictions.csv")

data.tail(20)
