# -*- coding: utf-8 -*-
"""GPT4omini_ZeroShot_Yoruba

Automatically generated by Colab.


# GPT-4o-mini — Zero-Shot Yoruba Dialect → English
Evaluating GPT-4o-mini as a **zero-shot baseline** on:
- Standard Yoruba → English
- Ilaje → English
- Ife → English

100 samples per dialect (300 total)

## Step 1 — Install & Setup
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q openai sacrebleu bert-score rouge-score
print('Done!')

OPENAI_API_KEY = 'your key'

from openai import OpenAI
client = OpenAI(api_key=OPENAI_API_KEY)

# Test connection
test = client.chat.completions.create(
    model='gpt-4o-mini',
    messages=[{'role': 'user', 'content': 'Say hello'}],
    max_tokens=10
)
print('API connected! Response:', test.choices[0].message.content)

"""## Step 2 — Load Dataset (100 samples per dialect)"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/yorulect.csv')
print('Shape:', df.shape)
print('Columns:', df.columns.tolist())
df.head()

# 100 samples per dialect
def get_samples(df, source_col, n=100, seed=42):
    data = []
    for _, row in df.iterrows():
        if pd.notna(row[source_col]) and pd.notna(row['english_text']):
            data.append({
                'source'    : row[source_col],
                'reference' : row['english_text']
            })
    # Fixed random sample for reproducibility
    import random
    random.seed(seed)
    return random.sample(data, min(n, len(data)))

std_data   = get_samples(df, 'std yoruba transcription', n=101)
ilaje_data = get_samples(df, 'Ilaje transcription',      n=101)
ife_data   = get_samples(df, 'Ife transcription',        n=101)

print(f'Std Yoruba : {len(std_data)} samples')
print(f'Ilaje      : {len(ilaje_data)} samples')
print(f'Ife        : {len(ife_data)} samples')
print('\nSample source  :', std_data[0]['source'])
print('Sample reference:', std_data[0]['reference'])

"""## Step 3 — GPT-4o-mini Zero-Shot


"""

import time

def run_gpt_inference(client, data, dialect_name):
    predictions, references = [], []
    print(f'\nRunning GPT-4o-mini inference for {dialect_name} ({len(data)} samples)...')

    for i, item in enumerate(data):
        try:

            prompt = (
                f'Translate this from {dialect_name} Yoruba to English.\n'
                f'{dialect_name} Yoruba: {item["source"]}\n'
                f'English:'
            )

            response = client.chat.completions.create(
                model='gpt-4o-mini',
                messages=[
                    {
                        'role': 'system',
                        'content': 'You are a professional translator. Translate the given Yoruba dialect text to English. Output only the English translation, nothing else.'
                    },
                    {
                        'role': 'user',
                        'content': prompt
                    }
                ],
                max_tokens=128,
                temperature=0.0   # deterministic output
            )

            pred = response.choices[0].message.content.strip()
            predictions.append(pred)
            references.append(item['reference'])

            if (i+1) % 10 == 0:
                print(f'  {i+1}/{len(data)} done...')

            # Small delay to avoid rate limiting
            time.sleep(0.5)

        except Exception as e:
            print(f'  Sample {i} failed: {e}')
            predictions.append('')
            references.append(item['reference'])

    print(f'{dialect_name} done — {len(predictions)} predictions')
    return predictions, references

std_preds,   std_refs   = run_gpt_inference(client, std_data,   'Standard')
ilaje_preds, ilaje_refs = run_gpt_inference(client, ilaje_data, 'Ilaje')
ife_preds,   ife_refs   = run_gpt_inference(client, ife_data,   'Ife')

# Preview predictions
for preds, refs, data, name in [
    (std_preds,   std_refs,   std_data,   'Std Yoruba'),
    (ilaje_preds, ilaje_refs, ilaje_data, 'Ilaje'),
    (ife_preds,   ife_refs,   ife_data,   'Ife')
]:
    print(f'\n── {name}')
    for i in range(min(3, len(preds))):
        print(f'  Source    : {data[i]["source"]}')
        print(f'  Reference : {refs[i]}')
        print(f'  Predicted : {preds[i]}')
        print()

"""## Step 4 — Evaluation Metrics"""

import numpy as np
from sacrebleu.metrics import BLEU, CHRF, TER
from bert_score import score as bert_score
from rouge_score import rouge_scorer

def compute_metrics(predictions, references, dialect_name):
    # Filter empty predictions
    pairs = [(p, r) for p, r in zip(predictions, references) if p.strip()]
    preds = [p for p, r in pairs]
    refs  = [r for p, r in pairs]

    print(f'  Evaluating {len(preds)} valid predictions...')

    bleu  = BLEU().corpus_score(preds, [refs]).score
    chrf  = CHRF(word_order=1).corpus_score(preds, [refs]).score
    _, _, F1 = bert_score(preds, refs, lang='en', verbose=False)
    bs_f1 = F1.mean().item()
    scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)
    rougeL = np.mean([scorer.score(r, p)['rougeL'].fmeasure for p, r in zip(preds, refs)])
    ter = TER().corpus_score(preds, [refs]).score

    print(f'\n── {dialect_name} Metrics ')
    print(f'  BLEU         : {bleu:.2f}')
    print(f'  chrF+        : {chrf:.2f}')
    print(f'  BERTScore F1 : {bs_f1:.4f}')
    print(f'  ROUGE-L      : {rougeL:.4f}')
    print(f'  TER (↓)      : {ter:.2f}')

    return {
        'Dialect'      : dialect_name,
        'BLEU'         : round(bleu, 2),
        'chrF+'        : round(chrf, 2),
        'BERTScore F1' : round(bs_f1, 4),
        'ROUGE-L'      : round(rougeL, 4),
        'TER (↓)'      : round(ter, 2)
    }

std_m   = compute_metrics(std_preds,   std_refs,   'Std Yoruba')
ilaje_m = compute_metrics(ilaje_preds, ilaje_refs, 'Ilaje')
ife_m   = compute_metrics(ife_preds,   ife_refs,   'Ife')

results_df = pd.DataFrame([std_m, ilaje_m, ife_m]).set_index('Dialect')
print('\n── GPT-4o-mini Zero-Shot Results')
print(results_df.to_string())

results_df.to_csv('/content/gpt4omini_results.csv')
print('\nSaved to /content/gpt4omini_results.csv')

"""## Step 5 — Save Predictions & Download"""

def save_predictions(preds, refs, data, filename):
    rows = []
    for pred, ref, item in zip(preds, refs, data):
        rows.append({
            'source_yoruba'     : item['source'],
            'reference_english' : ref,
            'predicted_english' : pred
        })
    df = pd.DataFrame(rows)
    df.to_csv(filename, index=False)
    print(f'Saved {filename} — {len(df)} rows')
    return df

std_df   = save_predictions(std_preds,   std_refs,   std_data,   '/content/gpt_std_predictions.csv')
ilaje_df = save_predictions(ilaje_preds, ilaje_refs, ilaje_data, '/content/gpt_ilaje_predictions.csv')
ife_df   = save_predictions(ife_preds,   ife_refs,   ife_data,   '/content/gpt_ife_predictions.csv')

# Download all
from google.colab import files
files.download('/content/gpt4omini_results.csv')
files.download('/content/gpt_std_predictions.csv')
files.download('/content/gpt_ilaje_predictions.csv')
files.download('/content/gpt_ife_predictions.csv')
print('All files downloaded!')
